### PR TITLE
Paolo initial commit

### PR DESCRIPTION
**Pull request by pzaino**
Tool from the past that I promised to make it available here and under Apache 2.0

### CODE REVIEW

**Review by skymandr — COMMENTED** [review]
Two questions:
1) Is this just old code committed as is, or are there new additions? If the latter, please point them out in the Diff.
2) How about tests? ;) It would be cool if we could get automated testing working, maybe a Github-action using Gerph's automated system, but I'm not sure if that is feasible.

**Comment by pzaino** [comment]
Good points.

So for your question 1, this is old code just recompiled to see if it works and it appears to be working so far.

For your question 2, yes I would like to add some tests, I contacted Charles RISC OS build Services which has a way to automate tests and integrate both builds and testing in a CI fashion on his Pyronmaniac platform. But yet no answer and so I was thinking we could add them later.

How that sounds?

Otherwise I can add later my rudimental desktop test automation done via !keystroke and classic test automation via CLI.

**Comment by skymandr** [comment]
> Good points.
> 
> So for your question 1, this is old code just recompiled to see if it works and it appears to be working so far.

Ok, thought as much.

> For your question 2, yes I would like to add some tests, I contacted Charles RISC OS build Services which has a way to automate tests and integrate both builds and testing in a CI fashion on his Pyronmaniac platform with github. But yet no answer and so I was thinking we could add them later.
> 
> How that sounds?

I think it sounds promising. I don't know the API for the RObS, so I'm not sure how simple it would be to automate. I might have a look tonight.

> 
> Otherwise I can add later my rudimental desktop test automation done via !keystroke and classic test automation via CLI.

I think a separate issue for testing this would probably be good.

**Review by skymandr — APPROVED** [review]
Looks good to me.

**Comment by pzaino** [comment]
> I might have a look tonight.

That would be lovely thanks!

**Pull request merged**
